[app]
exclude = "^/api/v1/decisions/get-flags|/api/v1/events/receive$"

[users.admin]
email = "admin@t.ru"
password = "admin"

[users.exp]
email = "exp@t.ru"
password = "exp"

[users.approver]
email = "approver@t.ru"
password = "approver"

[users.viewer]
email = "viewer@t.ru"
password = "viewer"

[users.approver2]
email = "approver2@t.ru"
password = "approver2"
