services:
  test-db:
    image: postgres:17
    hostname: test-db
    environment:
      POSTGRES_DB: alphabet
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - alphabet_main_net
    volumes:
      - test_pgdata:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d alphabet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  test-api:
    build: alphabet-backend
    command: ["./start_test.sh"]
    hostname: api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - alphabet_main_net
    configs:
      - source: app_conf
        target: /app/alphabet.yml
    environment:
      AB_POSTGRES__HOST: test-db
      AB_VALKEY__HOST: test-valkey
      AB_CLICKHOUSE__HOST: test-clickhouse
      AB_LOGGING__USE_JSON: false  # for easier visual debugging
      AB_NOTIFICATIONS__SMTP__HOST: test-mailpit
      COVERAGE_FILE: /app/.coverage_data/.coverage
    volumes:
      - ./.coverage_data:/app/.coverage_data
    depends_on:
      test-valkey:
        condition: service_healthy
      test-db:
        condition: service_healthy
      test-clickhouse:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 10s
      start_period: 5s
      retries: 3

  test-valkey:
    image: valkey/valkey:8.0
    hostname: test-valkey
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - test_valkey_data:/data
    environment:
      VALKEY_PASSWORD: valkey_pass
    networks:
      - alphabet_main_net
    healthcheck:
      test: [ "CMD", "valkey-cli", "-a", "valkey_pass", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  test-clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: test-clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - 8123
      - 9000
    volumes:
      - test_clickhouse_data:/var/lib/clickhouse
      - ./alphabet-backend/src/clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: chpass
    networks:
      - alphabet_main_net
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  test-mailpit:
    image: axllent/mailpit:latest
    hostname: test-mailpit
    restart: always
    environment:
      MP_MAX_MESSAGES: 5000
    expose:
      - "1025"
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - alphabet_main_net

volumes:
  test_pgdata:
  test_valkey_data:
  test_clickhouse_data:


networks:
  alphabet_main_net:
    driver: bridge


configs:
  app_conf:
    file: sys-tests/alphabet.test.yml
