services:
  db:
    image: postgres:17
    hostname: db
    environment:
      POSTGRES_DB: alphabet
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - alphabet_main_net
    volumes:
      - pgdata:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d alphabet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  api:
    build: alphabet-backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - alphabet_main_net
    configs:
      - source: app_conf
        target: /app/alphabet.yml
    environment:
      AB_POSTGRES__HOST: db
      AB_VALKEY__HOST: valkey
      AB_CLICKHOUSE__HOST: clickhouse
      AB_LOGGING__USE_JSON: true
      AB_NOTIFICATIONS__SMTP__HOST: mailpit
    depends_on:
      valkey:
        condition: service_healthy
      db:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  valkey:
    image: valkey/valkey:8.0
    hostname: valkey
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - valkey_data:/data
    environment:
      VALKEY_PASSWORD: valkey_pass
    networks:
      - alphabet_main_net
    healthcheck:
      test: [ "CMD", "valkey-cli", "-a", "valkey_pass", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - 8123
      - 9000
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./alphabet-backend/src/clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: chpass
    networks:
      - alphabet_main_net
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mailpit:
    image: axllent/mailpit:latest
    hostname: mailpit
    restart: always
    environment:
      MP_MAX_MESSAGES: 5000
    expose:
      - "1025"
    ports:
      - "8025:8025"
      - "1025:1025"


volumes:
  pgdata:
  valkey_data:
  clickhouse_data:


networks:
  alphabet_main_net:
    driver: bridge


configs:
  app_conf:
    file: alphabet-backend/alphabet.yml
