-- Generated by Gemini

CREATE TABLE IF NOT EXISTS events (
    id UUID,
    decision_id String,
    event_type String,
    variant_id String,
    issued_at DateTime64(3),
    received_at DateTime64(3),
    attributes String,
    status LowCardinality(String),
    wants_event_type Nullable(String)
) ENGINE = ReplacingMergeTree()
ORDER BY (event_type, decision_id, id);
