-- Generated by Gemini, then edited by Cursor and manually

-- ADR002: Count-based cooldown.
-- When subject receives N new experiment assignments, increment counter.
-- If counter >= threshold, set cooldown (TTL) and reset counter.
-- KEYS[1] = exp_count:{subject_id}
-- KEYS[2] = cooldown:{subject_id}
-- ARGV[1] = count (new assignments this request)
-- ARGV[2] = threshold (max assignments before cooldown)
-- ARGV[3] = cooldown_ttl_s
-- Returns: 1 if now in cooldown (we just triggered it), 0 otherwise

local count_key = KEYS[1]
local cooldown_key = KEYS[2]
local add_count = tonumber(ARGV[1])
local threshold = tonumber(ARGV[2])
local cooldown_ttl = tonumber(ARGV[3])

if redis.call("EXISTS", cooldown_key) == 1 then
    return 0  -- already in cooldown, caller handles
end

redis.call("INCRBY", count_key, add_count)
local total = tonumber(redis.call("GET", count_key) or 0)

if total >= threshold then
    redis.call("SET", cooldown_key, "1", "EX", cooldown_ttl)
    redis.call("DEL", count_key)
    return 1
end

return 0
