# type: ignore
"""create notifications

Revision ID: 99b9bb4b7d51
Revises: a3ca48c27097
Create Date: 2026-02-21 19:32:01.919143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99b9bb4b7d51'
down_revision: Union[str, Sequence[str], None] = 'a3ca48c27097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('trigger_resource', sa.String(), nullable=False),
    sa.Column('connection_string', sa.String(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('rate_limit_s', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_trigger_type'), 'notification_rules', ['trigger_type'], unique=False)
    op.create_table('prepared_notifications',
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fingerprint'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_prepared_notifications_rule_id'), 'prepared_notifications', ['rule_id'], unique=False)
    op.create_unique_constraint(None, 'audit_log', ['id'])
    op.create_unique_constraint(None, 'guard_rules', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guard_rules', type_='unique')
    op.drop_constraint(None, 'audit_log', type_='unique')
    op.drop_index(op.f('ix_prepared_notifications_rule_id'), table_name='prepared_notifications')
    op.drop_table('prepared_notifications')
    op.drop_index(op.f('ix_notification_rules_trigger_type'), table_name='notification_rules')
    op.drop_table('notification_rules')
    # ### end Alembic commands ###
