# type: ignore
"""create guard rules and audit

Revision ID: a3ca48c27097
Revises: 477a5f9ac756
Create Date: 2026-02-20 13:13:24.192270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3ca48c27097"
down_revision: Union[str, Sequence[str], None] = "477a5f9ac756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guard_rules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("metric_key", sa.String(), nullable=True),
        sa.Column("threshold", sa.Double(), nullable=True),
        sa.Column("watch_window_s", sa.Integer(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("PAUSE", "FORCE_CONTROL", name="guardaction"),
            nullable=True,
        ),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments_latest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rule_id", sa.String(), nullable=True),
        sa.Column("fired_at", sa.DateTime(), nullable=True),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("metric_key", sa.String(), nullable=True),
        sa.Column("metric_value", sa.Double(), nullable=True),
        sa.Column(
            "taken_action",
            sa.Enum("PAUSE", "FORCE_CONTROL", name="guardaction"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments_latest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["guard_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.alter_column(
        "metrics",
        "compiled",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.create_unique_constraint(None, "metrics", ["key"])
    op.create_unique_constraint(None, "reports", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reports", type_="unique")
    op.drop_constraint(None, "metrics", type_="unique")
    op.alter_column(
        "metrics",
        "compiled",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_table("audit_log")
    op.drop_table("guard_rules")
    # ### end Alembic commands ###
