# type: ignore
"""create event types

Revision ID: e8d32b73589f
Revises: 6d902520d9cc
Create Date: 2026-02-18 23:16:50.253290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8d32b73589f"
down_revision: Union[str, Sequence[str], None] = "6d902520d9cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_types",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("requires_attribution", sa.String(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "experiments_latest", ["id"])
    op.create_unique_constraint(None, "flags", ["key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "flags", type_="unique")
    op.drop_constraint(None, "experiments_latest", type_="unique")
    op.drop_table("event_types")
    # ### end Alembic commands ###
