@startuml
!include <C4/C4_Context>


Person(_2b93bb91, "Администратор", "Управляет пользователями, ролями, правилами ревью.",$tags="")

Person(_671628d4, "Экспериментатор", "Настраивает эксперименты, анализирует результаты.",$tags="")

Person(_db4cc232, "Утверждающий", "Ревьюит эксперименты, одобряет/отклоняет их.",$tags="")

Person(_3b36e8f4, "Наблюдатель", "Читает результаты.",$tags="")

Person(__06fa0f0b, "Клиентское приложение", "Отправляют пачки событий и запрашивают конфигурации флагов для пользователей.",$tags="")

System(_88480653, "Платформа", "Позволяет управлять каталогом событий, настраивать эксперименты,\nобрабатывать входящие события и визуализировать отчеты.",$tags="")

System_Ext(IAP, "IAP", "Корпоративная система аутентификации, обеспечивающая доступ сотрудников к внутренним ресурсам.",$tags="")

System_Ext(Telegram, "Telegram", "Мессенджер, цель уведомлений",$tags="")

System_Ext(__229c7f2d, "Почтовый сервер", "Почтовый сервер, цель уведомлений",$tags="")

Rel(_2b93bb91, _88480653, "","через IAP")

Rel(_2b93bb91, IAP, "","")

Rel(_671628d4, _88480653, "","через IAP")

Rel(_671628d4, IAP, "","")

Rel(_db4cc232, _88480653, "","через IAP")

Rel(_db4cc232, IAP, "","")

Rel(_3b36e8f4, _88480653, "","через IAP")

Rel(_3b36e8f4, IAP, "","")

Rel(__06fa0f0b, _88480653, "","")

Rel(_88480653, Telegram, "Отсылает уведомления","")

Rel(_88480653, __229c7f2d, "Отсылает уведомления","")

Rel(IAP, _88480653, "Проксирует аутентифицированные запросы","")

SHOW_LEGEND()
@enduml
