site_name: Alphabet dev docs
site_url: https://yt-redstone-mail-e7ec37.pages.prodcontest.com/
repo_url: https://gitlab.prodcontest.com/2026-final-users/backend/yt.redstone.mail
copyright: "&copy; Copyright Tapeline 2026"
nav:
  - Домашняя: index.md
  - Задание:
      - Условие: task/task.md
      - Критерии: task/criteria.md
  - Референс:
      - Глоссарий: glossary.md
      - Контроль доступа: usecases/01-access-control.md
      - Фича-флаги и эксперименты: usecases/02-feature-flags-experiments.md
      - Принятие решений и выдача: usecases/03-decision-making.md
      - События и статистика: usecases/04-stat-events.md
      - Отчёты: usecases/05-reports.md
      - Guardrails: usecases/06-guardrails.md
      - Уведомления: usecases/07-notifications.md
      - Insights UI: usecases/08-insights-ui.md
      - Разрешение конфликтов: usecases/11-conflicts-resolution.md
  - ADR:
      - Оглавление: adr/toc.md
      - 001 — Аутентификация: adr/001-auth.md
      - 002 — Выдача флагов: adr/002-decision.md
      - 003 — Строки подключения: adr/003-notification-dsl.md
      - 004 — Групп. оповещ.: adr/004-notification-grouping.md
      - 005 — Сбор событий: adr/005-events-collection.md
      - 006 — Оптимиз. событий: adr/006-event-type-query-opt.md
      - 007 — Разреш. конфликтов: adr/007-conflict-resolution.md
      - 008 — Insights UI: adr/008-insights.md
      - 009 — Evt. JSON Schema: adr/009-event-schema.md
  - Спецификации:
      - Оглавление: spec/toc.md
      - Метаязык определения DSL: spec/metalang.md
      - DSL оповещений: spec/notification-dsl.md
      - DSL таргетирования: spec/target-dsl.md
      - DSL метрик: spec/metric-dsl.md

theme:
  name: material2014
  primary_color: "#673AB7"


plugins:
  - mermaid2
  - ezglossary:
      ignore_case: true
      tooltip: full
  - search:
      lang:
        - en
        - ru
  - macros:
      module_name: macros


markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - def_list
  - material2014.extensions.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_include
