import asyncio
import logging
from typing import final, Final

from clickhouse_connect.driver import AsyncClient

# TODO: maybe move into config?
_WORKER_INTERVAL_S: Final = 60


@final
class AttributionWorker:
    def __init__(self, click: AsyncClient) -> None:
        self.click = click
        self.is_running = False
        self.logger = logging.getLogger("attribution_worker")

    async def start(self):
        self.is_running = True
        self.logger.info("Attribution worker started")
        while self.is_running:
            try:
                await self._run_attribution_cycle()
            except Exception as exc:
                self.logger.exception(
                    f"Attribution worker cycle failed.", exc_info=exc
                )
            await asyncio.sleep(_WORKER_INTERVAL_S)

    async def stop(self):
        self.is_running = False

    async def _run_attribution_cycle(self):
        # Generated by Gemini
        # TODO: review and edit, this is wrong!!!
        attribution_query = """
        INSERT INTO events
        SELECT
            child.id,
            child.decision_id,
            child.event_type,
            child.variant_id,
            child.issued_at,
            now64(3) as received_at,
            child.attributes,
            'Accepted' as status,
            child.wants_event_type
        FROM events AS child
        INNER JOIN (
            SELECT decision_id, event_type 
            FROM events 
            WHERE status = 'Accepted'
            GROUP BY decision_id, event_type
        ) AS parent ON child.decision_id = parent.decision_id 
                   AND child.wants_event_type = parent.event_type
        WHERE child.status = 'Pending'
        """

        expiration_query = """
        INSERT INTO events
        SELECT
            id,
            decision_id,
            event_type,
            variant_id,
            issued_at,
            now64(3),
            attributes,
            'Rejected_Expired' as status,
            wants_event_type
        FROM events
        WHERE status = 'Pending'
          AND issued_at < now() - INTERVAL 7 DAY
        """

        self.client.command(attribution_query)
        self.client.command(expiration_query)

        self.logger.debug("Цикл атрибуции успешно завершен")
